---
# Galaxy startup recipe

- name: Copy the startup script
  template: src=galaxy_startup.j2 dest=/usr/bin/galaxy-startup mode=a+x
  become_user: root
  become_method: sudo

#########################################################
# Stop services

#---
# CentOs 7

- name: Stop PostgreSQL server on CentOS
  shell: "{{pg_ctl_path}}/pg_ctl -D {{pgsql_pgdata}} stop" # the pg_ctl_path variable is defined in task/postgresql.yml
  become: True
  become_user: postgres
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04

- name: Stop PostgreSQL server on Ubuntu
  service: name=postgresql state=stopped enabled=no
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Stop NGINX server on Ubuntu
  service: name=nginx state=stopped enabled=no
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Stop Proftpd server on Ubuntu
  service: name=proftpd state=stopped enabled=no
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#########################################################
# Start Galaxy on VM

- name: Enable and start PostgreSQL server | vm
  service: name=postgresql enabled=yes state=started
  become_user: root
  become_method: sudo
  when: supervisor_manage_postgres == "False"

- name: Enable and start NGINX server | vm
  service: name=nginx state=started enabled=yes
  become_user: root
  become_method: sudo
  when: supervisor_manage_nginx == "False"

- name: Enable and start the proftpd server | vm
  service: name=proftpd enabled=yes state=started
  become_user: root
  become_method: sudo
  when: supervisor_manage_proftpd == "False"

- name: Start Galaxy | vm
  command: "/usr/bin/galaxy-startup"
  become_user: root
  become_method: sudo
  when: ansible_virtualization_type != "docker"
