---
# Nginx installation

# Modifications to the upstream (CentOS7) nginx package to add the upload (and possibly other) module(s).
# The package is built for CentOS7.

- name: Install NGINX dependencies
  yum: name={{item}}
       state=present
  with_items:
    - openssl-devel
    - pcre-devel
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Move NGINX rpm in /tmp
  copy: src=nginx-1.8.1-1.el7.centos.ngx.x86_64.rpm
        dest=/tmp/nginx-1.8.1-1.el7.centos.ngx.x86_64.rpm
  when: ansible_os_family == "RedHat"
  
- name: Install NGINX rpm from /tmp
  yum: name=/tmp/nginx-1.8.1-1.el7.centos.ngx.x86_64.rpm
       state=present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

# /etc/nginx/nginx.conf configuration

- name: Include NGINX specific variables.
  include_vars: nginx_vars.yml

- name: Copy the NGINX configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  become_user: root
  become_method: sudo

# modify galaxy.ini
- name: Edit galaxy.ini
  ini_file: dest={{galaxy_config_file}} section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
  with_items:
    - { section: 'app:main', option: 'nginx_upload_store', value: "database/tmp/upload_store" }
    - { section: 'app:main', option: 'nginx_upload_path', value: "/galaxy/_upload" }
    - { section: 'app:main', option: 'nginx_x_accel_redirect_base', value: "/_x_accel_redirect}" }
    - { section: 'app:main', option: 'nginx_x_archive_files_base', value: "/_x_accel_redirect" }
    - { section: 'app:main', option: 'filter-with', value: "proxy-prefix" }
    - { section: 'app:main', option: 'cookie_path', value: "/galaxy" }

- name: Create NGINX upload_store dir
  file: state=directory path={{nginx_upload_store_path}}

- name: Start NGINX | vm
  service: name=nginx state=started enabled=yes
  become_user: root
  become_method: sudo
  when: ansible_virtualization_type != "docker"
