---
#########################################################
# Install prerequisites

#---
#CentOS 7

- name: Install git, vim, wget
  yum: name={{item}}
       state=present
  with_items:
    - git
    - vim
    - wget
    - expect #mkpasswd utility
    - logrotate
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Install the 'Development tools' package group
  yum: name="@Development tools"
       state=present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04

- name: Install git, vim, wget, build-essential
  apt: name={{item}}
       state=present
  with_items:
    - apt-transport-https
    - software-properties-common
    - git
    - vim
    - wget
    - whois #mkpasswd utility
    - logrotate
    - build-essential
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"


#########################################################
# Create directories

- name: Create log directory
  file: path={{galaxy_log_path}}
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

- name: Create export directory
  file: path={{export_dir}}
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

- name: Create /etc/galaxy directory
  file: path=/etc/galaxy
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

#########################################################
# Configure Logrotate

- name: Copy logrotate configuration file
  template: src=logrotate.j2 dest=/etc/logrotate.d/galaxy
  become_user: root
  become_method: sudo
