---
#########################################################
# Proftpd configuration

#---
# CentOS 7

- name: Install proftpd
  yum: name={{item}}
       state=present
  with_items:
    - proftpd
    - proftpd-postgresql
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04

- name: Create proftpd db random passwd
  shell: mkpasswd -l 20 -s 0
  register: proftpd_db_passwd

- name: Copy the proftpd configuration file
  template: src=proftpd.conf.j2 dest={{proftpd_conf_path}}
  become_user: root
  become_method: sudo

- name: Create proftpd db user
  postgresql_user: db=galaxy
                   name={{proftpd_db_user}}
                   password={{proftpd_db_passwd.stdout}}
                   priv=galaxy_user:ALL
  become_user: postgres
  become_method: sudo

#- name: Enable and start the proftpd server
#  service: name=proftpd enabled=yes state=started
#  become_user: root
#  become_method: sudo
#  when: ansible_virtualization_type != "docker"
