---
# Proftpd installation and configuration recipe

#---
# CentOS 7
- name: Install proftpd
  yum: name={{item}}
       state=present
  with_items:
    - proftpd
    - proftpd-postgresql
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04
- name: Install proftpd
  apt: name={{item}}
       state=present
  with_items:
    - proftpd
    - proftpd-mod-pgsql
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"


#########################################################
# Install Proftpd

- name: Create proftpd db random passwd
  shell: "{{galaxy_venv_path}}/bin/python /usr/local/bin/pwd-generator -l 20"
  register: proftpd_db_passwd

- name: Copy the proftpd configuration file
  template: src=proftpd.conf.j2 dest={{proftpd_conf_path}}
  become_user: root
  become_method: sudo

- name: Create proftpd db user
  postgresql_user: db=galaxy
                   name={{proftpd_db_user}}
                   password={{proftpd_db_passwd.stdout}}
                   priv=galaxy_user:ALL
  become_user: postgres
  become_method: sudo
