---
# Supervisord installation and configuration recipe

#---
# CentOS 7
- name: Check and install Supervisor dependencies on CentOS7
  yum: name={{item}}
       state=present
  with_items:
    - supervisor
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Set supervisord conf path on CentOS
  set_fact: supervisord_conf_path=/etc
  when: ansible_os_family == "RedHat"

- name: Copy supervisord configuration file
  template: src=supervisord.conf.j2 dest=/etc/supervisord.d/galaxy_web.ini
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04
- name: Check and install Supervisor dependencies on Ubuntu
  apt: name={{item}}
       state=present
  with_items:
    - python-meld3
    - supervisor
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Set supervisord conf path on Ubuntu
  set_fact: supervisord_conf_path=/etc/supervisor
  when: ansible_os_family == "Debian"

- name: Copy supervisord configuration file
  template: src=supervisord.conf.j2 dest=/etc/supervisor/conf.d/galaxy_web.conf
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
